---
name: renovate-config-validator
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/workflows/renovate-config-validator.yaml
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
  workflow_dispatch:
permissions:
  contents: read
jobs:
  validate_renovate_config:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - .github/renovate.json5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        # yamllint disable-line rule:line-length
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: "24"
      # yamllint disable-line rule:line-length
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
        with:
          config_file_path: ${{ matrix.config }}
